-- FTS / Aktif Seferler - il/ilçe bazlı rota kilometre hafızası (v2)
-- Aynı rota = Yükleme İl + Yükleme İlçe + Teslim İl + Teslim İlçe.
-- Birden fazla yükleme/teslim varsa sıralı il/ilçe dizisinin tamamı anahtara dahildir.
-- Bu dosya eski tablo varsa da güvenle çalıştırılabilir.

create table if not exists public.rota_kilometreleri (
  id bigint generated by default as identity primary key,
  route_key text not null unique,
  route_label text,
  yukleme_ili text,
  yukleme_ilcesi text,
  teslim_ili text,
  teslim_ilcesi text,
  distance_km numeric(10,2) not null check (distance_km > 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.rota_kilometreleri add column if not exists yukleme_ili text;
alter table public.rota_kilometreleri add column if not exists yukleme_ilcesi text;
alter table public.rota_kilometreleri add column if not exists teslim_ili text;
alter table public.rota_kilometreleri add column if not exists teslim_ilcesi text;

-- v1 kayıtları nokta/firma bazlı farklı anahtar kullandığından v2 otomatik eşleşmesine girmez.
-- İsterseniz eski kayıtları temizlemek için aşağıdaki satırı bir kez ayrıca çalıştırabilirsiniz:
-- truncate table public.rota_kilometreleri restart identity;

alter table public.rota_kilometreleri enable row level security;

drop policy if exists "rota_kilometreleri_select" on public.rota_kilometreleri;
create policy "rota_kilometreleri_select" on public.rota_kilometreleri for select to authenticated, anon using (true);

drop policy if exists "rota_kilometreleri_insert" on public.rota_kilometreleri;
create policy "rota_kilometreleri_insert" on public.rota_kilometreleri for insert to authenticated, anon with check (true);

drop policy if exists "rota_kilometreleri_update" on public.rota_kilometreleri;
create policy "rota_kilometreleri_update" on public.rota_kilometreleri for update to authenticated, anon using (true) with check (true);
